
package org.javaee8recipes.chapter15.recipe15_01.endpoint;

import javax.jws.WebService;
import javax.jws.WebMethod;
import javax.jws.WebParam;

/**
 * JAX-WS service implementation class, generated by Netbeans
 * @author juneau
 */
@WebService(serviceName = "AuthorEndpoint")
public class Author {

    /**
     * This is a sample web service operation
     */
    @WebMethod(operationName = "hello")
    public String hello(@WebParam(name = "name") String txt) {
        return "Hello " + txt + " !";
    }
}
